### PR TITLE
FIX: Update svgutils after breaking API changes

### PR DESCRIPTION
**Pull request by mgxd**
Originally #619 (see https://github.com/nipreps/niworkflows/pull/619#issuecomment-777772466)

### CODE REVIEW

**Comment by effigies** [comment]
The SVGs from before have expired. When they regenerate, could you post them here as attachments to the comment, or screenshots?

**Comment by mgxd** [comment]
Essentially it seems to now be fixed, instead of dynamic based on window size.

master
this patch

**Comment by effigies** [comment]
Hmm. Not ideal.

**Comment by mgxd** [comment]
When comparing new/current images, it seemed the viewBox element was not being saved. Setting the height / width through svgutils' `Unit` fixes this, and images are correctly sized again. This should be good now.

**Review by effigies — APPROVED** [review]
LGTM. Thanks for tracking this down.

**Pull request merged**
