### PR TITLE
MAINT: Remove conditional dependencies on Python <3.6

### PR DESCRIPTION
**Pull request by oesteban**
~A new release of skimage is breaking or tests. Also,~ 

Remove leftovers of dependencies pinned for Python < 3.6 (#486)

### CODE REVIEW

**Comment by effigies** [comment]
I don't see 0.17 on PyPI. Where are the tests breaking?

**Comment by oesteban** [comment]
https://app.circleci.com/pipelines/github/oesteban/niworkflows/76/workflows/b9c076b1-b346-427d-b361-ce40d5b683e4/jobs/1602/steps

And weirdly, this one https://travis-ci.org/github/nipreps/niworkflows/builds/684491403 was failing yesterday.

**Comment by oesteban** [comment]
> I don't see 0.17 on PyPI. Where are the tests breaking?

May they have removed the release overnight? I'm pretty sure (100%) travis was pulling 0.17 from pypi yesterday.

**Comment by oesteban** [comment]
Okay, not crazy:

```
Collecting scikit-image (from niworkflows==1.2.0rc5+37.gfcfc43a)
  Downloading https://files.pythonhosted.org/packages/56/e0/c9f0ee148ca9b5d65c3971bfb4f2dba6df65b67dfb3a6c88a11deb31a73d/scikit_image-0.17.0-cp37-cp37m-manylinux1_x86_64.whl (12.3MB)
```

**Comment by oesteban** [comment]
Okay, rolled back the scikit-image pin. Only removing the python <3.6 leftovers. Thumbs-up?

**Comment by oesteban** [comment]
Okay, they just did it and it broke our builds - https://pypi.org/project/scikit-image/0.17.1/

**Comment by effigies** [comment]
Okay, so issues:

1) The cython issue is a scikit-image dependency called imagecodecs, which releases its wheels as manylinux2010 and manylinux2014, not manylinux1. This means we need pip 19 or higher. Unclear why the build environment is not being created properly
2) Now scikit-image creates a directory on import, which fails in parallel as pytest-xdist (https://github.com/scikit-image/scikit-image/issues/4660). The failing call is in a project called Pooch (https://github.com/fatiando/pooch/issues/170) and is fixed in master (https://github.com/fatiando/pooch/pull/171). A short-term fix is to add a `python -c "import skimage"` before testing. The long-term fix is waiting for pooch to release, which I suspect will be soon.

I'll make a quick PR.

**Comment by jni** [comment]
Great sleuthing @effigies and apologies for the churn here! We are making pooch an optional dependency in scikit-image/scikit-image#4666, (and backporting to 0.17.2) which should hopefully fix all the directory creation issues as long as you aren't running the full skimage test suite.

imagecodecs comes via tifffile which is harder to avoid. I hope you were able to work around that?

**Pull request merged**
