### PR TITLE
fix: skip t1w file existence check if anat_derivatives are provided

### PR DESCRIPTION
**Pull request by bpinsard**
Changes to allow processing dataset without T1w series if `--anat_derivatives` are provided.
See https://github.com/poldracklab/fmriprep/pull/2201

### CODE REVIEW

**Comment by effigies** [comment]
@mgxd Should we target 1.3.0 or 1.2.7 with this?

**Comment by mgxd** [comment]
I think this is fine for either, but since the behavior will not be included into the 20.1.x series of fmriprep, I'm leaning towards 1.3.0 - wdyt?

**Comment by effigies** [comment]
Sure. I just haven't kept up with the current status of dependencies. Merging into master.

**Comment by mgxd** [comment]
oh, nevermind - it's in 😄

**Comment by effigies** [comment]
Suggestion LGTM. Feel free to patch on master.

**Pull request merged**
