### PR TITLE
ENH: Allow passing a ``database_path`` to create a ``BIDSLayout``

### PR DESCRIPTION
**Pull request by oesteban**
Resolves: #786.

### CODE REVIEW

**Comment by oesteban** [comment]
Works locally:

```Text
230311-00:34:47,353 nipype.workflow INFO:
         [Node] Executing "metadata" <niworkflows.interfaces.bids.ReadSidecarJSON>
230311-00:34:47,359 nipype.workflow INFO:
         [Node] Finished "metadata", elapsed time 0.005727s.
```

This node used to take ~50s on the main thread and ~80s on workers.

**Comment by effigies** [comment]
Don't you need to hook it up to something?

**Comment by oesteban** [comment]
What do you mean?

From pybids, this doesn't require anything specific other than a release supporting `database_path`. From MRIQC/xPreps just to set the `config.execution.bids_database_dir` (or wherever name that config has) at workflow definition

**Comment by oesteban** [comment]
It'd be prudent to deprecate the `layout` member of the interface though - it can only be used with the linear plugging of nipype

**Comment by effigies** [comment]
Sorry, I thought this was on mriqc.

**Pull request merged**
